image: bitriseio/docker-android:v2020_02_15-08_05-b1936
# you can find latest docker image at https://hub.docker.com/r/bitriseio/docker-android/tags
# to ensure backward compatability we should always use a concrete docker image version and NOT latest!

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

stages:
  - test
  - deploy

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper
    - .gradle/caches

merge_request:
  stage: test
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "*/build/reports"
  tags:
    - kvm
  only:
    - merge_requests
  script:
    # build
    - ./gradlew clean detekt testDebugUnitTest lintDebug assembleDebug assembleAndroidTest

deploy_release:
  stage: deploy
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - "*/build/reports"
      - "*/build/outputs/aar"
  tags:
    - kvm
  only:
    - tags
  script:
    # build
    - ./gradlew clean testReleaseUnitTest assembleRelease assembleAndroidTest
    - ./gradlew uploadArchives