import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.5.0" // available: "0.7.0"

  const val com_android_tools_build_gradle: String = "3.6.2"

  const val navigation_fragment_ktx: String = "2.2.0" // available: "2.2.1"

  const val androidx_test_ext_junit: String = "1.1.1"

  const val org_jetbrains_kotlin: String = "1.3.71"

  const val espresso_core: String = "3.2.0"

  const val core_testing: String = "2.1.0"

  const val assertj_core: String = "3.15.0"

  const val lint_gradle: String = "26.6.2"

  const val junit_junit: String = "4.13"

  const val core_ktx: String = "1.2.0"

  const val timber: String = "4.7.1"

  const val aapt2: String = "3.6.2-6040484"

  const val event: String = "0.1.0"

  const val mockk: String = "1.9.3"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "6.3"

  const val gradleCurrentVersion: String = "5.6.4"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
